namespace: service

commonLabels: {}
podAnnotations: {}
imagePullSecrets:
  - packages-ghcr-pull

app:
  name: sre

api:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/service-sre-api
    tag: sha-edeba7948238c6a876469e10a98cc2d231929f6b # sre-api-image
    pullPolicy: Always
  port: 3333
  service:
    port: 3333
  env:
    PORT: "3333"
    SRE_REQUIRED_SCOPE: sre:admin
  envSecretRefs:
    SRE_DATABASE_URL_AUTH:
      secretName: sre-api-env
      secretKey: DATABASE_URL_AUTH
      optional: false
  readinessProbe:
    path: /api/v1/health
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    path: /api/v1/health
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 192Mi

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/service-sre-web
    tag: sha-9a3d3edfe4e2b498d03b5f833f6a96bfe806ffee # sre-web-image
    pullPolicy: Always
  port: 80
  service:
    port: 80
  env:
    SRE_API_INTERNAL_URL: http://sre-api:3333
  readinessProbe:
    path: /
    initialDelaySeconds: 2
    periodSeconds: 5
  livenessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

middleware:
  enabled: true
  name: sre-forward-auth
  address: http://auth-api.service.svc.cluster.local:3333/internal/auth/session/check
  authResponseHeaders:
    - X-Auth-Subject
    - X-Auth-Type
    - X-Auth-Scopes
    - X-Auth-Email
    - X-Auth-Profile-Id

ingress:
  className: traefik
  host: sre.liberte.top
  tls:
    enabled: true
    secretName: sre-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  protected:
    enabled: true
    middlewareRef: service-sre-forward-auth@kubernetescrd
  public:
    enabled: false
    path: /api/v1/health
    pathType: Exact
