namespace: service

commonLabels: {}
podAnnotations: {}
imagePullSecrets:
  - packages-ghcr-pull

app:
  name: registry

api:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/app-registry-api
    tag: sha-a11f5af30659b855d17c6031176e7b13e48bcfbe # registry-api-image
    pullPolicy: Always
  port: 4320
  service:
    port: 4320
  env:
    PORT: "4320"
    REGISTRY_ADMIN_SCOPE: registry:admin
    MINI_PACKAGES_INTERNAL_URL: http://packages-api:3333
    MINI_PACKAGES_PUBLIC_URL: https://packages.liberte.top
    MINI_CRATES_INTERNAL_URL: http://crates-api:3333
    MINI_CRATES_PUBLIC_URL: https://crates.liberte.top
  envSecretRefs:
    MINI_PACKAGES_ADMIN_TOKEN:
      secretName: packages-api-env
      secretKey: BOOTSTRAP_ADMIN_TOKEN
      optional: false
    MINI_CRATES_ADMIN_TOKEN:
      secretName: crates-kellnr-env
      secretKey: KELLNR_SETUP__ADMIN_TOKEN
      optional: false
  readinessProbe:
    path: /api/v1/health
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    path: /api/v1/health
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/app-registry-web
    tag: sha-a11f5af30659b855d17c6031176e7b13e48bcfbe # registry-web-image
    pullPolicy: Always
  port: 80
  service:
    port: 80
  readinessProbe:
    path: /
    initialDelaySeconds: 2
    periodSeconds: 5
  livenessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

middleware:
  enabled: true
  name: registry-forward-auth
  address: http://auth-api.service.svc.cluster.local:3333/internal/auth/session/check
  authResponseHeaders:
    - X-Auth-Subject
    - X-Auth-Type
    - X-Auth-Scopes
    - X-Auth-Email
    - X-Auth-Profile-Id

ingress:
  className: traefik
  host: registry.liberte.top
  tls:
    enabled: true
    secretName: registry-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  protected:
    enabled: true
    middlewareRef: service-registry-forward-auth@kubernetescrd
  public:
    enabled: true
    path: /api/v1/health
    pathType: Exact
