apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "packages.componentName" (dict "root" . "component" "verdaccio-config") }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "packages.labels" (dict "root" . "component" "verdaccio-config") | indent 4 }}
data:
  config.yaml: |
    storage: /verdaccio/storage
    plugins: /usr/local/lib/node_modules

    auth:
      htpasswd:
        file: /verdaccio/auth/htpasswd
        max_users: {{ .Values.verdaccio.auth.maxUsers }}
        algorithm: bcrypt
        rounds: 12

    store:
      aws-s3-storage:
        bucket: VERDACCIO_S3_BUCKET
        keyPrefix: VERDACCIO_S3_KEY_PREFIX
        region: VERDACCIO_S3_REGION
        endpoint: VERDACCIO_S3_ENDPOINT
        s3ForcePathStyle: {{ .Values.verdaccio.s3.forcePathStyle }}
        accessKeyId: VERDACCIO_S3_ACCESS_KEY_ID
        secretAccessKey: VERDACCIO_S3_SECRET_ACCESS_KEY

    packages:
      '@*/*':
        access: $authenticated
        publish: $authenticated
        unpublish: $authenticated
        storage: scoped
      '**':
        access: $authenticated

    middlewares:
      audit:
        enabled: false

    web:
      enable: false

    log:
      type: stdout
      format: pretty
      level: http
