apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "packages.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ include "packages.ingressAnnotations" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "packages.componentName" (dict "root" . "component" "api") }}
                port:
                  number: {{ .Values.api.service.port }}
{{ include "packages.ingressTls" . | indent 2 }}
