apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
  namespace: service
  labels:
    app: auth-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-web
  template:
    metadata:
      labels:
        app: auth-web
    spec:
      containers:
        - name: auth-web
          image: ghcr.io/liberte-top/service-auth-web:sha-51ff14e3e21f12bd464ff10413c9a4528fc43076
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
