namespace: service

commonLabels: {}
podAnnotations: {}
imagePullSecrets: []

app:
  name: crates

api:
  replicaCount: 1
  image:
    repository: ghcr.io/perishcode/mini-crates-api
    tag: latest # crates-api-image
    pullPolicy: Always
  port: 3333
  service:
    port: 3333
  env:
    PORT: "3333"
    DATABASE_HOST: postgres.core.svc.cluster.local
    DATABASE_PORT: "5432"
    DATABASE_NAME: kellnr
    REGISTRY_PUBLIC_URL: https://crates.liberte.top
    S3_REGION: auto
    S3_FORCE_PATH_STYLE: "true"
  envSecretRefs:
    DATABASE_USER:
      secretName: crates-kellnr-env
      secretKey: KELLNR_POSTGRESQL__USER
      optional: false
    DATABASE_PASSWORD:
      secretName: crates-kellnr-env
      secretKey: KELLNR_POSTGRESQL__PWD
      optional: false
    BOOTSTRAP_ADMIN_TOKEN:
      secretName: crates-kellnr-env
      secretKey: KELLNR_SETUP__ADMIN_TOKEN
      optional: false
    TOKEN_PEPPER:
      secretName: crates-kellnr-env
      secretKey: KELLNR_REGISTRY__COOKIE_SIGNING_KEY
      optional: false
    S3_ENDPOINT:
      secretName: crates-kellnr-env
      secretKey: KELLNR_S3__ENDPOINT
      optional: false
    S3_BUCKET:
      secretName: crates-kellnr-env
      secretKey: KELLNR_S3__CRATES_BUCKET
      optional: false
    S3_ACCESS_KEY_ID:
      secretName: crates-kellnr-env
      secretKey: KELLNR_S3__ACCESS_KEY
      optional: false
    S3_SECRET_ACCESS_KEY:
      secretName: crates-kellnr-env
      secretKey: KELLNR_S3__SECRET_KEY
      optional: false
  readinessProbe:
    path: /-/ping
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    path: /-/ping
    initialDelaySeconds: 15
    periodSeconds: 20
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  className: traefik
  host: crates.liberte.top
  tls:
    enabled: true
    secretName: crates-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
