apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singbox-api
  namespace: service
  labels:
    app: singbox-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: singbox-api
  template:
    metadata:
      labels:
        app: singbox-api
    spec:
      containers:
        - name: singbox-api
          image: ghcr.io/liberte-top/singbox-api:latest
          ports:
            - containerPort: 3333
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: singbox-api
  namespace: service
spec:
  selector:
    app: singbox-api
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  type: ClusterIP
