apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service
  namespace: argocd
spec:
  project: liberte-top
  sources:
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: manifests/service/namespace
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/service/auth
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/app/smoke
      helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: service
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
