apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service
  namespace: argocd
spec:
  project: liberte-top
  source:
    repoURL: https://github.com/liberte-top/kubernetes.git
    targetRevision: main
    path: manifests/service
  destination:
    server: https://kubernetes.default.svc
    namespace: service
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
