apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service
  namespace: argocd
spec:
  project: liberte-top
  sources:
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: manifests/service
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/service/auth
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/app/smoke
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/app/registry
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/app/design
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/service/packages
      helm: {}
    - repoURL: https://github.com/liberte-top/kubernetes.git
      targetRevision: main
      path: charts/service/crates
      helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
