apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-redirect
  namespace: service
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: service
  labels:
    app: auth-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: ghcr.io/liberte-top/auth-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: service
spec:
  selector:
    app: auth-api
  ports:
    - name: http
      port: 3333
      targetPort: 3333
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-web
  namespace: service
  labels:
    app: auth-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-web
  template:
    metadata:
      labels:
        app: auth-web
    spec:
      containers:
        - name: auth-web
          image: ghcr.io/liberte-top/auth-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-web
  namespace: service
spec:
  selector:
    app: auth-web
  ports:
    - name: http
      port: 8888
      targetPort: 8888
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: service
spec:
  secretName: auth-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - auth.liberte.top
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: service
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: service-auth-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.liberte.top
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: auth-api
                port:
                  number: 3333
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-web
                port:
                  number: 8888
  tls:
    - secretName: auth-tls
      hosts:
        - auth.liberte.top
