apiVersion: v1
kind: Namespace
metadata:
  name: service
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-redirect
  namespace: service
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-placeholder
  namespace: service
  labels:
    app: auth-placeholder
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-placeholder
  template:
    metadata:
      labels:
        app: auth-placeholder
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: auth-placeholder
  namespace: service
spec:
  selector:
    app: auth-placeholder
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: service
spec:
  secretName: auth-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - auth.liberte.top
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: service
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: service-auth-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: auth.liberte.top
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: auth-placeholder
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-placeholder
                port:
                  number: 80
  tls:
    - secretName: auth-tls
      hosts:
        - auth.liberte.top
