apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha-deployer
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-deployer
  namespace: services
rules:
  - apiGroups:
      - ""
      - apps
      - networking.k8s.io
    resources:
      - deployments
      - services
      - configmaps
      - secrets
      - pods
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-deployer
  namespace: services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gha-deployer
subjects:
  - kind: ServiceAccount
    name: gha-deployer
    namespace: services
