namespace: service

commonLabels: {}
podAnnotations: {}

app:
  name: smoke

api:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/app-smoke-api
    tag: sha-7d2d8b31ab72fe8e908f51fa2cd534951573dcb6 # smoke-api-image
    pullPolicy: Always
  port: 4310
  service:
    port: 4310
  env:
    PORT: "4310"
  readinessProbe:
    path: /api/v1/health
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    path: /api/v1/health
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/app-smoke-web
    tag: sha-6cefa644965a8adf9eda79e9550ab655ded47a0c # smoke-web-image
    pullPolicy: Always
  port: 80
  service:
    port: 80
  readinessProbe:
    path: /
    initialDelaySeconds: 2
    periodSeconds: 5
  livenessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

middleware:
  enabled: true
  name: smoke-forward-auth
  address: http://auth-api.service.svc.cluster.local:3333/internal/auth/session/check
  authResponseHeaders:
    - X-Auth-Subject
    - X-Auth-Type
    - X-Auth-Scopes
    - X-Auth-Email
    - X-Auth-Profile-Id

ingress:
  className: traefik
  host: smoke.liberte.top
  tls:
    enabled: true
    secretName: smoke-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  protected:
    enabled: true
    middlewareRef: service-smoke-forward-auth@kubernetescrd
  public:
    enabled: true
    path: /api/v1/health
    pathType: Exact
