apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: liberte-top
  namespace: argocd
spec:
  description: liberte.top platform workloads
  sourceRepos:
    - https://github.com/liberte-top/kubernetes.git
  destinations:
    - namespace: core
      server: https://kubernetes.default.svc
    - namespace: service
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
