apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash-web
  namespace: services
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: clash-web
  template:
    metadata:
      labels:
        app: clash-web
    spec:
      containers:
        - name: clash-web
          image: nginx:alpine
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - |
              cat >/etc/nginx/conf.d/default.conf <<'EOF'
              server {
                listen 80;
                location / {
                  add_header Content-Type text/plain;
                  return 200 "ok\n";
                }
              }
              EOF
              nginx -g 'daemon off;'
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
