namespace: service

commonLabels: {}
podAnnotations: {}
imagePullSecrets: []

app:
  name: packages

api:
  replicaCount: 1
  image:
    repository: ghcr.io/perishcode/mini-packages-api
    tag: sha-547b99e5c4f97cf0db233720711444060062f915 # packages-api-image
    pullPolicy: Always
  port: 3333
  service:
    port: 3333
  secretName: packages-api-env
  env:
    PORT: "3333"
    REGISTRY_PUBLIC_URL: https://packages.liberte.top
    S3_FORCE_PATH_STYLE: "true"
  readinessProbe:
    path: /-/ping
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    path: /-/ping
    initialDelaySeconds: 15
    periodSeconds: 20
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  className: traefik
  host: packages.liberte.top
  tls:
    enabled: true
    secretName: packages-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
