apiVersion: v1
kind: Namespace
metadata:
  name: smoke
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-nginx
  namespace: smoke
  labels:
    app: smoke-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoke-nginx
  template:
    metadata:
      labels:
        app: smoke-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: smoke-nginx
  namespace: smoke
spec:
  selector:
    app: smoke-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
