apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: auth-api
          image: ghcr.io/perishcode/liberte.top/auth-api:latest
          imagePullPolicy: Always
          env:
            - name: BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: auth-basic-auth
                  key: BASIC_AUTH_USER
            - name: BASIC_AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-basic-auth
                  key: BASIC_AUTH_PASS
            - name: SESSION_TTL_SECONDS
              value: "3600"
            - name: SESSION_COOKIE_DOMAIN
              value: ".liberte.top"
            - name: REDIRECT_HOST_SUFFIX
              value: ".liberte.top"
            - name: DEFAULT_REDIRECT_URL
              value: "https://clash.liberte.top/"
            - name: REDIS_HOST
              value: "redis.infra.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "1"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clash-redis
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 3200
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3200
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3200
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
