namespace: service

commonLabels: {}
podAnnotations: {}

app:
  name: auth

ingress:
  className: traefik
  host: auth.liberte.top
  tls:
    enabled: true
    secretName: auth-liberte-top-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

api:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/service-auth-api
    tag: sha-c834fe99ac51c79ac65d9192306bd8c2a89a5ce2 # auth-api-image
    pullPolicy: Always
  port: 3333
  service:
    port: 3333
    portName: http
  probe:
    type: http
  env:
    PORT: "3333"
    MAIL_GRPC_ADDR: http://auth-mail:50051
    FORWARDAUTH_SESSION_COOKIE_NAME: liberte_session
    FORWARDAUTH_SESSION_COOKIE_DOMAIN: .liberte.top
    FORWARDAUTH_LOGIN_URL: https://auth.liberte.top/
    EMAIL_FROM: Auth <auth@mail.liberte.top>
    EMAIL_VERIFY_BASE_URL: https://auth.liberte.top/auth/verify/email
    EMAIL_LOGIN_BASE_URL: https://auth.liberte.top/auth/login/email/complete
    EMAIL_TOKEN_TTL_SECS: "900"
  secretEnv:
    DATABASE_URL:
      secretName: auth-api-env
      secretKey: DATABASE_URL
    RESEND_API_KEY:
      secretName: auth-api-env
      secretKey: RESEND_API_KEY
  readinessProbe:
    path: /api/v1/health
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    path: /api/v1/health
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

mail:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/service-mail
    tag: sha-d4a53a1c5f7fda4841252c608e27b46b111e44ae # service-mail-image
    pullPolicy: Always
  port: 50051
  service:
    port: 50051
    portName: grpc
  probe:
    type: tcp
  env:
    PORT: "50051"
    EMAIL_FROM: Auth <auth@mail.liberte.top>
  secretEnv:
    RESEND_API_KEY:
      secretName: auth-api-env
      secretKey: RESEND_API_KEY
  readinessProbe:
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/liberte-top/service-auth-web
    tag: sha-88ff04425ce8e64cc58bf586c34d12c569d30d6d # auth-web-image
    pullPolicy: Always
  port: 80
  service:
    port: 80
    portName: http
  probe:
    type: http
  readinessProbe:
    path: /
    initialDelaySeconds: 2
    periodSeconds: 5
  livenessProbe:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
