apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-web
  namespace: service
  labels:
    app: smoke-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoke-web
  template:
    metadata:
      labels:
        app: smoke-web
    spec:
      containers:
        - name: smoke-web
          image: ghcr.io/liberte-top/app-smoke-web:sha-8a2c657ad5d9255e155260574ed56a01a4eccd7d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
